### ISSUE TITLE
Connect to Secure NiFi using Username/Password

### ISSUE THREAD

**Issue by AndrewMcCutcheon** [microsoft/MonitoFi#3]
Hi

I cannot see how to connect a NiFi instance using Username / Password.

Is this possible?  We do not use certificate based login but username / password.

Thanks

**Comment by AndrewMcCutcheon** [comment]
Hi.  I have been able to work around this.  Not a pretty as the original code, but working.  Perhaps you could add to the code with a switch to enable it.

Within the python script, I modified the while loop to take in to account the requesting of a JWT token and using that in the process.

Please see code snippet below:

while conditions[MODE]():
    try:
        for AURL in API_URL:
            #Get token to connect
            data = "username=<username>&password=<password>"
            token = requests.post(url=AURL + "/access/token", headers={
                'Content-Type': 'application/x-www-form-urlencoded'}, data=data,
                verify=False)
            for ENDPOINT in ENDPOINT_LIST:
                bearer = "Bearer " + token.content.decode("utf-8")
                r = requests.get(url=AURL + ENDPOINT) if SECURE == False else get(url=AURL + ENDPOINT, headers={
                    'Content-Type': 'application/json',
                    'Authorization': bearer
                    }, verify=False)
                received_response = r.json()
                flat_response = flattening(received_response, "", [])
                current_time = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
                points = [{
                "measurement": ENDPOINT,
                "tags": {'APIURL':AURL},
                "time": current_time,
                "fields": flat_response
                }]
                logger.info(ENDPOINT, extra=received_response)
                iclient.write_points(points)
            if IKEY != "REPLACE_ME":
                handler.flush()
            count += 1

**Comment by tushardhadiwal** [comment]
@AndrewMcCutcheon Thanks for raising the issue. I am glad you were able to modify the request to include authentication method required for your cluster. We will add support for the same in upcoming update. Thanks!
